import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Cookie Stand Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="content-center p-2 text-3xl bg-emerald-500">
        <h1 className='mt-2'> Cookie Stand Admin </h1>
      </header>

      <main>
        {/*form section*/}
        <div className='p-4 my-8 mx-28 bg-emerald-300'>
          <p className='text-2xl font-bold text-center'>
            Creat Cookie Stand
          </p>
          <form className=''>
          <label>Location</label>
          <input className='' type="text" name="loc" />
          <br></br>
          <div className='justify-between'>
          <label className='mx-3'>Minimum Customers per Hour</label>
          <label className='mx-3'>Maximum Customers per Hour</label>
          <label className='mx-3'>Average Cookies per Sale</label>
          </div>
          
          <input className='flex-auto mx-3' type="text" name="minimum" />
          <input className='flex-auto mx-3' type="text" name="maximum" />
          <input className='flex-auto mx-3' type="text" name="avg" />
          
          <button type="submit" className='px-16 py-2 bg-emerald-500'>Create</button>
          </form>
        </div>
        {/*paragraph section*/}
        <p className='text-center'>
          Report Table Coming Soon...
        </p>
        {/* JSON section*/}
      </main>

      <footer className='p-4 bg-emerald-500'>
        <p>copyright 2022</p>
      </footer>
    </div>
  )
}
